[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_package"
version = "0.1.0"
description = "A short description of the package"
authors = [
  {name = "Your Name", email = "your.email@example.com"},
]
requires-python = ">=3.6"
dependencies = ["somepackage>=1.0"]

[tool.setuptools.packages.find]
where = ["."]