version: '3'
 
services:
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ekpedeutikoi
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend


  # Server:
  # Username: local
  # Password: local
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      # PMA_USER: root
      # PMA_PASSWORD: root
    restart: always
    ports:
      - 8081:80
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata: