# #!/bin/bash
make import.qualifications SPEC="ΠΕ01" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ01 ΘΕΟΛΟΓΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ02" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ02 ΦΙΛΟΛΟΓΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ03" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ03 ΜΑΘΗΜΑΤΙΚΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ04.01" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ04 ΦΥΣΙΚΩΝ ΕΠΙΣΤΗΜΩΝ _ ΠΕ04.01 ΦΥΣΙΚΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ04.02" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ04 ΦΥΣΙΚΩΝ ΕΠΙΣΤΗΜΩΝ _ ΠΕ04.02 ΧΗΜΙΚΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ04.03" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ04 ΦΥΣΙΚΩΝ ΕΠΙΣΤΗΜΩΝ _ ΠΕ04.03 ΦΥΣΙΟΓΝΩΣΤΕΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ04.04" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ04 ΦΥΣΙΚΩΝ ΕΠΙΣΤΗΜΩΝ _ ΠΕ04.04 ΒΙΟΛΟΓΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ04.05" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ04 ΦΥΣΙΚΩΝ ΕΠΙΣΤΗΜΩΝ _ ΠΕ04.05 ΓΕΩΛΟΓΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ05" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ05 ΓΑΛΛΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ06" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ06 ΑΓΓΛΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ07" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ07 ΓΕΡΜΑΝΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ08" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ08 ΚΑΛΛΙΤΕΧΝΙΚΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ11" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ11 ΦΥΣΙΚΗΣ ΑΓΩΓΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ33" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ33 ΙΣΤΟΡΙΑΣ ΚΑΙ ΦΙΛΟΣΟΦΙΑΣ ΤΗΣ ΕΠΙΣΤΗΜΗΣ ΜΕΘΟΔΟΛΟΓΙΑΣ_ΙΣΤΟΡΙΑΣ ΚΑΙ ΘΕΩΡΙΑΣ ΤΗΣ ΕΠΙΣΤΗΜΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ34" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ34 ΙΤΑΛΙΚΗΣ ΦΙΛΟΛΟΓΙΑΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ40" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ40 ΙΣΠΑΝΙΚΗΣ ΦΙΛΟΛΟΓΙΑΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ41" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ41 ΘΕΩΡΙΑΣ ΚΑΙ ΙΣΤΟΡΙΑΣ ΤΗΣ ΤΕΧΝΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ78" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ78 ΚΟΙΝΩΝΙΚΩΝ ΕΠΙΣΤΗΜΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ80" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ80 ΟΙΚΟΝΟΜΙΑΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ81" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ81 ΠΟΛ.ΜΗΧΑΝΙΚΩΝ-ΑΡΧΙΤΕΚΤΟΝΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ82" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ82 ΜΗΧΑΝΟΛΟΓΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ83" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ83 ΗΛΕΚΤΡΟΛΟΓΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ84" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ84 ΗΛΕΚΤΡΟΝΙΚΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ85" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ85 ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ86" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ86 ΠΛΗΡΟΦΟΡΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.01" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.01 ΙΑΤΡΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.02" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.02 ΝΟΣΗΛΕΥΤΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.03" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.03 ΑΙΣΘΗΤΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.04" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.04 ΙΑΤΡΙΚΩΝ ΕΡΓΑΣΤΗΡΙΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.05" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.05 ΟΔΟΝΤΟΤΕΧΝΙΚΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.06" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.06 ΚΟΙΝΩΝΙΚΗΣ ΕΡΓΑΣΙΑΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.07" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.07 ΡΑΔΙΟΛΟΓΙΑΣ-ΑΚΤΙΝΟΛΟΓΙΑΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.08" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.08 ΦΥΣΙΟΘΕΡΑΠΕΙΑΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.09" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.09 ΒΡΕΦΟΝΗΠΙΟΚΟΜΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ87.10" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ87 ΥΓΕΙΑΣ-ΠΡΟΝΟΙΑΣ-ΕΥΕΞΙΑΣ _ ΠΕ87.10 ΔΗΜΟΣΙΑΣ ΥΓΙΕΙΝΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ88.01" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ88 ΓΕΩΠΟΝΙΑΣ, ΔΙΑΤ_ΦΗΣ & ΠΕΡΙΒ. _ ΠΕ88.01 ΓΕΩΠΟΝΟΙ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ88.02" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ88 ΓΕΩΠΟΝΙΑΣ, ΔΙΑΤ_ΦΗΣ & ΠΕΡΙΒ. _ ΠΕ88.02 ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ88.03" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ88 ΓΕΩΠΟΝΙΑΣ, ΔΙΑΤ_ΦΗΣ & ΠΕΡΙΒ. _ ΠΕ88.03 ΖΩΙΚΗΣ ΠΑΡΑΓΩΓΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ88.04" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ88 ΓΕΩΠΟΝΙΑΣ, ΔΙΑΤ_ΦΗΣ & ΠΕΡΙΒ. _ ΠΕ88.04 ΔΙΑΤΡΟΦΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ88.05" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ88 ΓΕΩΠΟΝΙΑΣ, ΔΙΑΤ_ΦΗΣ & ΠΕΡΙΒ. _ ΠΕ88.05 ΦΥΣΙΚΟΥ ΠΕΡΙΒ_ΝΤΟΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ89.01" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ89 ΕΦΑΡΜ. ΤΕΧΝΩΝ _ ΠΕ89.01 ΚΑΛΛΙΤΕΧΝΙΚΩΝ ΣΠΟΥΔΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ89.02" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ89 ΕΦΑΡΜ. ΤΕΧΝΩΝ _ ΠΕ89.02 ΣΧΕΔ_ΜΟΥ & ΠΑΡΑΓ. ΠΡΟΪΟΝΤΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ90" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ90 ΝΑΥΤΙΚΩΝ ΜΑΘΗΜΑΤΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ91.01" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ91 ΘΕΑΤΡΙΚΗΣ ΑΓΩΓΗΣ _ ΠΕ91.01 ΘΕΑΤΡΙΚΩΝ ΣΠΟΥΔΩΝ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";
make import.qualifications SPEC="ΠΕ91.02" FILE="anaplirotes/2GE_2026_PROSORINOI/1_ΚΑΤ_ΠΕ91 ΘΕΑΤΡΙΚΗΣ ΑΓΩΓΗΣ _ ΠΕ91.02 ΔΡΑΜΑΤΙΚΗΣ ΤΕΧΝΗΣ_ΓΕΝ (ΜΕ ΕΜΠ.)_ΒΠ.xls";