"""Initial migration

Revision ID: 349b88137e66
Revises: 
Create Date: 2024-08-22 16:49:56.205915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349b88137e66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'educator',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('lastname', sa.String(length=255), nullable=True),
        sa.Column('father', sa.String(length=255), nullable=True),
        sa.Column('adt', sa.String(length=255), nullable=True),
        sa.Column('penalty', sa.Boolean(), nullable=False),
        sa.Column('hired', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educator_adt'), 'educator', ['adt'], unique=False)


    op.create_table(
        "qualifications",
        # Primary key
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),

        # Educator
        sa.Column("educator_id", sa.Integer(), nullable=True),

        # Metadata
        sa.Column("year_of_import", sa.String(length=255), nullable=True),
        sa.Column("pinakas_katataksis", sa.String(length=255), nullable=True),
        sa.Column("file", sa.String(length=255), nullable=True),

        # Academic qualifications
        sa.Column("vasikos_titlos_spoudon", sa.Float(), nullable=True),
        sa.Column("deutero_ptyxio_aei", sa.Float(), nullable=True),
        sa.Column("didaktoriko_diploma", sa.Float(), nullable=True),
        
        # arithmos_autotelon_metaptyxiakon_titlon_i_integrated_masters_eos_2
        sa.Column("arithmos_autotelon_metaptyxiakon_titlon_i_integrated_masters", sa.Integer(), nullable=True),
        sa.Column("monades_metaptyxiakon_titlon_synolika", sa.Float(), nullable=True),
        sa.Column("ptyxio_paidagogikou_eae_monon_gia_pe61_pe71", sa.Boolean(), nullable=True),
        sa.Column("ptyxio_tefaa_me_kyria_eidikotita_eae_monon_gia_pe11", sa.Boolean(), nullable=True),
        sa.Column("epimorfosi_aei_toulaxiston_300_oron_7_minon", sa.Float(), nullable=True),
        sa.Column("synolo_monadon_akadimaikon_prosonton", sa.Float(), nullable=True),

        # Foreign languages
        sa.Column("aristi_gnosi_xenon_glosson", sa.Integer(), nullable=True),
        sa.Column("poly_kali_gnosi_xenon_glosson", sa.Integer(), nullable=True), 
        sa.Column("kali_gnosi_xenon_glosson", sa.Integer(), nullable=True), 
        sa.Column("synolo_monadon_xenon_glosson_eos_2", sa.Float(), nullable=True),

        # Computer skills 
        sa.Column("gnosi_xeirismou_iy", sa.Float(), nullable=True),

        # Teaching experience 
        sa.Column("mines_ekpaideutikis_proypiresias", sa.Float(), nullable=True), 
        sa.Column("monades_ekpaideutikis_proypiresias", sa.Float(), nullable=True), 
        sa.Column("mines_ekpaideutikis_proypiresias_se_dysprosita", sa.Float(), nullable=True), 
        sa.Column("monades_ekpaideutikis_proypiresias_se_dysprosita", sa.Float(), nullable=True),

        # 3-month contracts 2020-2021 
        sa.Column("mines_ekp_proyp_3minis_diarkeias_2020_2021", sa.Float(), nullable=True), 
        sa.Column("monades_ekp_proyp_3minis_diarkeias_2020_2021", sa.Float(), nullable=True),

        # 3-month contracts 2021-2022 
        sa.Column("mines_ekp_proyp_3minis_diarkeias_2021_2022", sa.Float(), nullable=True), 
        sa.Column("monades_ekp_proyp_3minis_diarkeias_2021_2022", sa.Float(), nullable=True),

        # 3-month contracts / hard-to-reach 2020-2021 
        sa.Column("mines_ekp_proyp_3minis_diarkeias_dysprosita_2020_2021", sa.Float(), nullable=True), 
        sa.Column("monades_ekp_proyp_3minis_diarkeias_dysprosita_2020_2021", sa.Float(), nullable=True),

        # 3-month contracts / hard-to-reach 2021-2022 
        sa.Column("mines_ekp_proyp_3minis_diarkeias_dysprosita_2021_2022", sa.Float(), nullable=True), 
        sa.Column("monades_ekp_proyp_3minis_diarkeias_dysprosita_2021_2022", sa.Float(), nullable=True),

        # Private education 
        sa.Column("mines_ekp_proyp_stin_idiotiki_ekpaideusi", sa.Float(), nullable=True), 
        sa.Column("monades_ekp_proyp_stin_idiotiki_ekpaideusi", sa.Float(), nullable=True),

        # Digital tutoring 
        sa.Column("mines_ekp_proyp_sto_psifiako_frontistirio", sa.Float(), nullable=True), 
        sa.Column("monades_ekp_proyp_sto_psifiako_frontistirio", sa.Float(), nullable=True), 
        sa.Column("synolo_monadon_ekpaideutikis_proypiresias", sa.Float(), nullable=True),

        # Children 
        sa.Column("arithmos_teknon", sa.Integer(), nullable=True), 
        sa.Column("monades_teknon", sa.Float(), nullable=True),

        # Disability
        sa.Column("pososto_anapirias", sa.Float(), nullable=True),
        sa.Column("monades_anapirias", sa.Float(), nullable=True),

        # Special qualifications
        sa.Column("protaksi_logo_paidagogikis_didaktikis_eparkeias", sa.Boolean(), nullable=True),
        sa.Column("braille", sa.Boolean(), nullable=True),
        sa.Column("elliniki_noimatiki_glossa", sa.Boolean(), nullable=True),

        # Ranking / lottery
        sa.Column("seira_ilektronikis_klirosis_par_4_arthr_15_n_4765_2021", sa.Integer(), nullable=True), 
    )
    op.create_index("ix_qualifications_educator_id", "qualifications", ["educator_id"], unique=False)
    op.create_index("ix_qualifications_year_of_import", "qualifications", ["year_of_import"], unique=False)
    op.create_index("ix_qualifications_pinakas_katataksis", "qualifications", ["pinakas_katataksis"], unique=False)

    
    # op.create_table(
    #     'school_hire',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('am', sa.String(length=255), nullable=True),
    #     sa.Column('file', sa.String(length=255), nullable=True),
    #     sa.Column('school_year', sa.String(length=255), nullable=True),
    #     sa.Column('round', sa.Integer(), nullable=True),
    #     sa.Column('location', sa.String(length=255), nullable=True),
    #     sa.Column('state', sa.String(length=255), nullable=True),
    #     sa.Column('management_sector', sa.String(length=255), nullable=True),
    #     sa.Column('working_hours', sa.String(length=255), nullable=True),
    #     sa.Column('aa', sa.String(length=255), nullable=True),
    #     sa.Column('aa_row', sa.String(length=255), nullable=True),
    #     sa.Column('department', sa.String(length=255), nullable=True),
    #     sa.Column('specification', sa.String(length=255), nullable=True),
    #     sa.Column('main_table_score', sa.String(length=255), nullable=True),
    #     sa.Column('main_table_order', sa.String(length=255), nullable=True),
    #     sa.Column('main_table_type', sa.String(length=255), nullable=True),
    #     sa.Column('main_table', sa.String(length=255), nullable=True),
    #     sa.Column('hired', sa.Boolean(), nullable=True),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('school_hire')
    
    op.drop_index("ix_qualifications_educator_id", table_name="qualifications")
    op.drop_index("ix_qualifications_year_of_import", table_name="qualifications")
    op.drop_index("ix_qualifications_pinakas_katataksis", table_name="qualifications")
    op.drop_table('qualifications')

    op.drop_index("ix_educator_adt", table_name="educator")
    op.drop_table('educator')
    # ### end Alembic commands ###
