"""Initial migration

Revision ID: 349b88137e66
Revises: 
Create Date: 2024-08-22 16:49:56.205915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349b88137e66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('am', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('father', sa.String(length=255), nullable=True),
    sa.Column('adt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('am', sa.String(length=255), nullable=True),
    sa.Column('year_of_import', sa.String(length=255), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('total_score_of_academic', sa.Float(), nullable=True),
    sa.Column('is_amea', sa.Float(), nullable=True),
    sa.Column('number_of_kids', sa.Float(), nullable=True),
    sa.Column('degree_first', sa.Float(), nullable=True),
    sa.Column('degree_second', sa.Float(), nullable=True),
    sa.Column('degree_master', sa.Float(), nullable=True),
    sa.Column('degree_doctor', sa.Float(), nullable=True),
    sa.Column('experience_in_months', sa.Float(), nullable=True),
    sa.Column('score_for_experience', sa.Float(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_hire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('am', sa.String(length=255), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('school_year', sa.String(length=255), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('management_sector', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('aa', sa.String(length=255), nullable=True),
    sa.Column('aa_row', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('main_table_score', sa.String(length=255), nullable=True),
    sa.Column('main_table_order', sa.String(length=255), nullable=True),
    sa.Column('main_table_type', sa.String(length=255), nullable=True),
    sa.Column('main_table', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_hire')
    op.drop_table('qualifications')
    op.drop_table('educator')
    # ### end Alembic commands ###
