"""adding hire table

Revision ID: 3f4d278fd98f
Revises: 9c73da59871e
Create Date: 2026-08-12 14:47:01.287637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f4d278fd98f'
down_revision: Union[str, Sequence[str], None] = '9c73da59871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('school_year', sa.String(length=255), nullable=True),
    sa.Column('round', sa.String(length=255), nullable=True),
    sa.Column('aa', sa.Integer(), nullable=True),
    sa.Column('aa_row', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('main_table_type', sa.String(length=255), nullable=True),
    sa.Column('main_table', sa.String(length=255), nullable=True),
    sa.Column('main_table_order', sa.Integer(), nullable=True),
    sa.Column('main_table_score', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('management_sector', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hires_department'), 'hires', ['department'], unique=False)
    op.create_index(op.f('ix_hires_educator_id'), 'hires', ['educator_id'], unique=False)
    op.create_index(op.f('ix_hires_location'), 'hires', ['location'], unique=False)
    op.create_index(op.f('ix_hires_round'), 'hires', ['round'], unique=False)
    op.create_index(op.f('ix_hires_school_year'), 'hires', ['school_year'], unique=False)
    op.create_index(op.f('ix_hires_specialization'), 'hires', ['specialization'], unique=False)
    op.create_index(op.f('ix_hires_state'), 'hires', ['state'], unique=False)
    op.drop_table('school_hire')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_hire',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('am', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hired', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('school_year', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('round', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('management_sector', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('working_hours', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('aa', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('aa_row', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('specification', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('main_table_score', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('main_table_order', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('main_table_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('main_table', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_index(op.f('ix_hires_state'), table_name='hires')
    op.drop_index(op.f('ix_hires_specialization'), table_name='hires')
    op.drop_index(op.f('ix_hires_school_year'), table_name='hires')
    op.drop_index(op.f('ix_hires_round'), table_name='hires')
    op.drop_index(op.f('ix_hires_location'), table_name='hires')
    op.drop_index(op.f('ix_hires_educator_id'), table_name='hires')
    op.drop_index(op.f('ix_hires_department'), table_name='hires')
    op.drop_table('hires')
    # ### end Alembic commands ###
