"""Database Migration adding penalty and hire column

Revision ID: 4be58268031f
Revises: 349b88137e66
Create Date: 2024-08-22 16:59:51.542475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be58268031f'
down_revision: Union[str, None] = '349b88137e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educator', sa.Column('penalty', sa.Boolean(), nullable=False))
    op.add_column('educator', sa.Column('hired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('educator', 'hired')
    op.drop_column('educator', 'penalty')
    # ### end Alembic commands ###
