"""Database Migration 

Revision ID: 524e389c6718
Revises: 4be58268031f
Create Date: 2024-08-24 14:16:53.801212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524e389c6718'
down_revision: Union[str, None] = '4be58268031f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_educator_adt'), 'educator', ['adt'], unique=False)
    op.create_index(op.f('ix_educator_am'), 'educator', ['am'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_educator_am'), table_name='educator')
    op.drop_index(op.f('ix_educator_adt'), table_name='educator')
    # ### end Alembic commands ###
