"""

Revision ID: 89248d82b80a
Revises: f1beabfaf8b9
Create Date: 2026-08-11 16:16:24.013423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89248d82b80a'
down_revision: Union[str, Sequence[str], None] = 'f1beabfaf8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('specialization', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_qualifications_specialization'), 'qualifications', ['specialization'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_specialization'), table_name='qualifications')
    op.drop_column('qualifications', 'specialization')
    # ### end Alembic commands ###
