"""change order in list to aa

Revision ID: 93fd41007d08
Revises: cbe9241872b8
Create Date: 2026-08-12 22:16:52.056956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93fd41007d08'
down_revision: Union[str, Sequence[str], None] = 'cbe9241872b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('aa', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_hires_am_order_in_list'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_order_in_list'), table_name='qualifications')
    op.create_index(op.f('ix_qualifications_aa'), 'qualifications', ['aa'], unique=False)
    op.create_index('ix_qualifications_am_aa', 'qualifications', ['am', 'aa'], unique=False)
    op.drop_column('qualifications', 'order_in_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('order_in_list', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index('ix_qualifications_am_aa', table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_aa'), table_name='qualifications')
    op.create_index(op.f('ix_qualifications_order_in_list'), 'qualifications', ['order_in_list'], unique=False)
    op.create_index(op.f('ix_hires_am_order_in_list'), 'qualifications', ['am', 'order_in_list'], unique=False)
    op.drop_column('qualifications', 'aa')
    # ### end Alembic commands ###
