"""

Revision ID: 9c73da59871e
Revises: b12be423cd56
Create Date: 2026-08-12 07:29:40.522519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c73da59871e'
down_revision: Union[str, Sequence[str], None] = 'b12be423cd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('total_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualifications', 'total_score')
    # ### end Alembic commands ###
