"""

Revision ID: a65d4ea0b19a
Revises: 3f4d278fd98f
Create Date: 2026-08-12 16:00:04.219142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65d4ea0b19a'
down_revision: Union[str, Sequence[str], None] = '3f4d278fd98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('am', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_qualifications_am'), 'qualifications', ['am'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_am'), table_name='qualifications')
    op.drop_column('qualifications', 'am')
    # ### end Alembic commands ###
