"""Database Migration 

Revision ID: a7dafaf06b3f
Revises: 524e389c6718
Create Date: 2024-08-24 14:58:23.344499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dafaf06b3f'
down_revision: Union[str, None] = '524e389c6718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_qualifications_am'), 'qualifications', ['am'], unique=False)
    op.create_index(op.f('ix_qualifications_spec'), 'qualifications', ['spec'], unique=False)
    op.create_index(op.f('ix_qualifications_year_of_import'), 'qualifications', ['year_of_import'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_year_of_import'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_spec'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_am'), table_name='qualifications')
    # ### end Alembic commands ###
