"""adding default values

Revision ID: b12be423cd56
Revises: f9c71b7b10b5
Create Date: 2026-08-11 17:27:02.838941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b12be423cd56'
down_revision: Union[str, Sequence[str], None] = 'f9c71b7b10b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualifications', 'braille',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('qualifications', 'elliniki_noimatiki_glossa',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualifications', 'elliniki_noimatiki_glossa',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('qualifications', 'braille',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
