"""adding order_in_list with index

Revision ID: cbe9241872b8
Revises: a65d4ea0b19a
Create Date: 2026-08-12 21:45:30.961288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe9241872b8'
down_revision: Union[str, Sequence[str], None] = 'a65d4ea0b19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifications', sa.Column('order_in_list', sa.Integer(), nullable=True))
    op.create_index('ix_hires_am_order_in_list', 'qualifications', ['am', 'order_in_list'], unique=False)
    op.create_index(op.f('ix_qualifications_order_in_list'), 'qualifications', ['order_in_list'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_order_in_list'), table_name='qualifications')
    op.drop_index('ix_hires_am_order_in_list', table_name='qualifications')
    op.drop_column('qualifications', 'order_in_list')
    # ### end Alembic commands ###
