"""

Revision ID: df62558905e8
Revises: 93fd41007d08
Create Date: 2026-08-17 07:59:09.609556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df62558905e8'
down_revision: Union[str, Sequence[str], None] = '93fd41007d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('1'), 'hires', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('1'), 'hires', 'educator', ['educator_id'], ['id'])
    # ### end Alembic commands ###
