"""Adding table hires

Revision ID: f1beabfaf8b9
Revises: 349b88137e66
Create Date: 2026-08-11 15:43:19.646754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1beabfaf8b9'
down_revision: Union[str, Sequence[str], None] = '349b88137e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educator', 'penalty',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('educator', 'hired',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educator', 'hired',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('educator', 'penalty',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
