"""Adding more indexes in educators

Revision ID: f9c71b7b10b5
Revises: 89248d82b80a
Create Date: 2026-08-11 16:18:20.733798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c71b7b10b5'
down_revision: Union[str, Sequence[str], None] = '89248d82b80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_educator_father'), 'educator', ['father'], unique=False)
    op.create_index(op.f('ix_educator_lastname'), 'educator', ['lastname'], unique=False)
    op.create_index(op.f('ix_educator_name'), 'educator', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_educator_name'), table_name='educator')
    op.drop_index(op.f('ix_educator_lastname'), table_name='educator')
    op.drop_index(op.f('ix_educator_father'), table_name='educator')
    # ### end Alembic commands ###
